up:
	. ./media/.smol/venv/bin/activate
	uvicorn app.main:app --reload --log-level debug --host 0.0.0.0 --port 8000

build:
	cd frontend && npm ci && npm run build
	mkdir -p media/.smol/static
	cp -r frontend/dist/* media/.smol/static
	python -m venv media/.smol/venv
	ls ./media/.smol/venv/bin/
	. ./media/.smol/venv/bin/activate
	pip install -r requirements.txt