"""RENAME_ME

Revision ID: 6dc68d69ae18
Revises: ff02edc363ba
Create Date: 2025-06-21 11:26:05.580491

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '6dc68d69ae18'
down_revision: Union[str, None] = 'ff02edc363ba'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('thumbnail_path', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media', 'thumbnail_path')
    # ### end Alembic commands ###
