"""RENAME_ME

Revision ID: 70b51c6758b2
Revises: 94d1f4d9ef32
Create Date: 2025-10-17 16:33:30.691427

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.exc import OperationalError

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "70b51c6758b2"
down_revision: Union[str, None] = "94d1f4d9ef32"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    try:
        op.create_table(
            "duplicateignore",
            sa.Column("media_id_a", sa.Integer(), nullable=False),
            sa.Column("media_id_b", sa.Integer(), nullable=False),
            sa.Column("created_at", sa.DateTime(), nullable=False),
            sa.ForeignKeyConstraint(
                ["media_id_a"],
                ["media.id"],
            ),
            sa.ForeignKeyConstraint(
                ["media_id_b"],
                ["media.id"],
            ),
            sa.PrimaryKeyConstraint("media_id_a", "media_id_b"),
        )
    # ### end Alembic commands ###
    except OperationalError:
        print("Table duplicateignore already exists!")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("duplicateignore")
    # ### end Alembic commands ###
