"""RENAME_ME

Revision ID: ff02edc363ba
Revises:
Create Date: 2025-06-19 15:38:43.468998

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff02edc363ba"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "person",
        sa.Column(
            "appearance_count",
            sa.Integer(),
            nullable=False,
            server_default="0",
        ),
    )
    op.create_index(
        "person_appearance_count_idx", "person", ["appearance_count"]
    )
    print("Populating appearance_count for existing persons...")
    op.execute(
        """
        UPDATE person
        SET appearance_count = (
            SELECT count(id)
            FROM face
            WHERE face.person_id = person.id
        )
    """
    )
    print("Population complete.")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("person", "appearance_count")
    # ### end Alembic commands ###
